import type { LucideIcon } from "lucide-react";

/**
 * Single source of truth model for the course content.
 *
 * Every `CourseEntry` represents one formula and OPTIONALLY carries a calculator
 * linked to it:
 *  - WITHOUT `calculate` → the entry appears only on the Formulas page.
 *  - WITH `calculate`    → the same entry appears on both the Formulas and the
 *    Calculations page, so a formula on one page and its calculation on the other
 *    are automatically LINKED (they are not two independent objects).
 *
 * Consistency rule: the `formula` text and `calculate()` always compute the same
 * quantity in the same unit. Unit conversions are stated in the `note` field.
 */

export interface FormulaVariable {
  symbol: string;
  label: string;
  unit?: string;
}

export interface CalcInput {
  key: string;
  label: string;
  unit?: string;
  placeholder?: string;
  /** Optional numeric bounds; the shared calculator applies them in the UI and in validation. */
  min?: number;
  max?: number;
  step?: number | "any";
  /** Defaults to true. Use false only for fields that are genuinely optional. */
  required?: boolean;
  /** Short operational help for the source of the input or its sign/unit convention. */
  help?: string;
}

export interface CalcResult {
  label: string;
  value: string;
}

/**
 * A single solution step. The `steps()` generator returns the ordered intermediate
 * steps from the entered values; every step is deterministic (computed in code, not
 * generated by AI).
 *
 *  - `title`      → the step heading, e.g. "1) Local Hour Angle (LHA)".
 *  - `expression` → the expression with the values substituted, e.g. "LHA = GHA + λ = 158.5°".
 *  - `result`     → the intermediate result of that step (highlighted).
 *  - `hint`       → a short "why" explanation (fixed, instructional text).
 */
export interface CalcStep {
  title: string;
  expression?: string;
  result?: string;
  hint?: string;
}

/** A real standard/source reference (to prevent invented rules and formulas). */
export interface SourceRef {
  code: string;
  detail?: string;
  url?: string;
}

export interface CourseEntry {
  /** Stable slug, e.g. "carnot-efficiency". */
  id: string;
  name: string;
  /** Formula group heading, e.g. "Laws of Thermodynamics". */
  group: string;
  /** Display expression, e.g. "η = 1 − (T_L / T_H)". */
  formula: string;
  variables: FormulaVariable[];
  source?: SourceRef;
  note?: string;
  /** Inputs of the linked calculator (provided together with calculate). */
  inputs?: CalcInput[];
  calculate?: (vals: Record<string, number>) => CalcResult[];
  /**
   * OPTIONAL step-by-step solution generator. It works from the same inputs as
   * `calculate` and always produces the same quantity in the same unit (the result
   * of the last step is identical to the `calculate` result). When defined, the
   * "Show the solution step by step" option appears on the calculator card.
   */
  steps?: (vals: Record<string, number>) => CalcStep[];
}

/** The subtitle and bullet list of a rule group. */
export interface RuleSection {
  subtitle: string;
  content: string[];
}

/** Rule category (compatible with the existing machine RuleCategory shape). */
export interface RuleGroup {
  title: string;
  source?: SourceRef;
  rules: RuleSection[];
}

export interface CourseTopic {
  /** Unified registry key: machine = slug, deck = category id. */
  key: string;
  title: string;
  icon: LucideIcon;
  /** Tailwind gradient class (the same as in the existing config). */
  accent: string;
  group: "deck" | "machine";
  intro?: string;
  entries: CourseEntry[];
  /** Optional: a link to the advanced/legacy tool page. */
  advancedTool?: { label: string; href: string };
}
