// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/compass-conversion.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";
var compass_conversion_default = defineTool({
  name: "compass_conversion",
  title: "Compass \u2194 Magnetic \u2194 True conversion",
  description: "Convert between Compass, Magnetic and True headings using variation and deviation (CDMVT rule). Provide exactly one of compass, magnetic or true.",
  inputSchema: {
    compass: z.number().min(0).max(360).nullable().describe("Compass heading in degrees, or null."),
    magnetic: z.number().min(0).max(360).nullable().describe("Magnetic heading in degrees, or null."),
    trueHeading: z.number().min(0).max(360).nullable().describe("True heading in degrees, or null."),
    variation: z.number().describe("Variation in degrees. East is positive, West is negative."),
    deviation: z.number().describe("Deviation in degrees. East is positive, West is negative.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ compass, magnetic, trueHeading, variation, deviation }) => {
    const given = [compass, magnetic, trueHeading].filter((v) => v !== null).length;
    if (given !== 1) {
      return {
        content: [{ type: "text", text: "Provide exactly one of compass, magnetic, or trueHeading." }],
        isError: true
      };
    }
    const norm = (v) => (v % 360 + 360) % 360;
    let C, M, T;
    if (compass !== null) {
      C = compass;
      M = norm(C + deviation);
      T = norm(M + variation);
    } else if (magnetic !== null) {
      M = magnetic;
      C = norm(M - deviation);
      T = norm(M + variation);
    } else {
      T = trueHeading;
      M = norm(T - variation);
      C = norm(M - deviation);
    }
    const summary = `Compass ${C.toFixed(1)}\xB0 | Magnetic ${M.toFixed(1)}\xB0 | True ${T.toFixed(1)}\xB0 (Var ${variation}\xB0, Dev ${deviation}\xB0)`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { compass: C, magnetic: M, trueHeading: T, variation, deviation }
    };
  }
});

// src/lib/mcp/tools/great-circle-distance.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var EARTH_RADIUS_NM = 3440.065;
var great_circle_distance_default = defineTool2({
  name: "great_circle_distance",
  title: "Great-circle distance",
  description: "Compute the great-circle distance (in nautical miles) and initial bearing (degrees true) between two lat/lon points.",
  inputSchema: {
    lat1: z2.number().min(-90).max(90).describe("Latitude of point 1 in decimal degrees."),
    lon1: z2.number().min(-180).max(180).describe("Longitude of point 1 in decimal degrees."),
    lat2: z2.number().min(-90).max(90).describe("Latitude of point 2 in decimal degrees."),
    lon2: z2.number().min(-180).max(180).describe("Longitude of point 2 in decimal degrees.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lat1, lon1, lat2, lon2 }) => {
    const toRad = (d) => d * Math.PI / 180;
    const toDeg = (r) => r * 180 / Math.PI;
    const \u03C61 = toRad(lat1);
    const \u03C62 = toRad(lat2);
    const \u0394\u03C6 = toRad(lat2 - lat1);
    const \u0394\u03BB = toRad(lon2 - lon1);
    const a = Math.sin(\u0394\u03C6 / 2) ** 2 + Math.cos(\u03C61) * Math.cos(\u03C62) * Math.sin(\u0394\u03BB / 2) ** 2;
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    const distanceNm = EARTH_RADIUS_NM * c;
    const y = Math.sin(\u0394\u03BB) * Math.cos(\u03C62);
    const x = Math.cos(\u03C61) * Math.sin(\u03C62) - Math.sin(\u03C61) * Math.cos(\u03C62) * Math.cos(\u0394\u03BB);
    const bearing = (toDeg(Math.atan2(y, x)) + 360) % 360;
    const summary = `Distance ${distanceNm.toFixed(2)} NM, initial bearing ${bearing.toFixed(1)}\xB0 True`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { distanceNm, initialBearingTrue: bearing }
    };
  }
});

// src/lib/mcp/tools/speed-time-distance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var speed_time_distance_default = defineTool3({
  name: "speed_time_distance",
  title: "Speed / Time / Distance",
  description: "Solve for the missing value in the speed\u2013time\u2013distance relationship. Speed in knots, time in hours, distance in nautical miles. Provide exactly two of the three.",
  inputSchema: {
    speedKnots: z3.number().positive().nullable().describe("Speed in knots, or null."),
    timeHours: z3.number().positive().nullable().describe("Time in hours, or null."),
    distanceNm: z3.number().positive().nullable().describe("Distance in nautical miles, or null.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ speedKnots, timeHours, distanceNm }) => {
    const given = [speedKnots, timeHours, distanceNm].filter((v) => v !== null).length;
    if (given !== 2) {
      return {
        content: [{ type: "text", text: "Provide exactly two of speedKnots, timeHours, distanceNm." }],
        isError: true
      };
    }
    let s = speedKnots, t = timeHours, d = distanceNm;
    if (s === null) s = d / t;
    else if (t === null) t = d / s;
    else d = s * t;
    const summary = `Speed ${s.toFixed(2)} kn \xB7 Time ${t.toFixed(2)} h \xB7 Distance ${d.toFixed(2)} NM`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { speedKnots: s, timeHours: t, distanceNm: d }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vrpbhguztsqakvjcezeb";
var mcp_default = defineMcp({
  name: "mariners-book-mcp",
  title: "Mariner's Book MCP",
  version: "0.1.0",
  instructions: "Maritime calculation tools from Mariner's Book. Use `great_circle_distance` for lat/lon distance and bearing, `compass_conversion` for CDMVT True/Magnetic/Compass conversions, and `speed_time_distance` to solve the speed/time/distance triangle.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [great_circle_distance_default, compass_conversion_default, speed_time_distance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
